### ISSUE TITLE
No dynamic variable values in key action: HTTP Post

### ISSUE THREAD

**Issue by krzyzz** [bitfocus/companion-module-generic-http#6]
I suppose it's designed this way, but apparently dynamic variables only work in Companion button's text field.
Whenever I put the desired variable of $(x:y) in Key down action: HTTP Post URI field, the variable is being passed literally as written.

For example:
![image](https://user-images.githubusercontent.com/71986307/95657001-50550c80-0b12-11eb-8dda-c2affb20e153.png)
is interpretted by HTTP server as:
![image](https://user-images.githubusercontent.com/71986307/95657106-f7d23f00-0b12-11eb-80e5-07650deaac55.png)

If it only worked as planned, Bitfocus would be an ideal tally server/proxy/distributor/w/e that passed lights to my smartviews, GPI devices etc...

**Comment by JeffreyDavidsz** [comment]
The generic module is not for these kind of actions. You should request a module for it. This way other users would benefit to. I've added variable to tally option in thingm blink module, so a light will go on when a variable hits a (dynamic) value. Just as a example. Building a separate module with button press at the moment. Closing this issue because it more a general request
